name: Deploy to HuggingFace Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKENG }} 
        run: |
          git config --global user.email "dharnilotpal31@gmail.com"
          git config --global user.name "nilotpaldhar2004"

          # 1. Clone the HuggingFace Space
          git clone https://huggingface.co/spaces/nilotpaldhar2004/Deep-Learning-for-Skin-Lesion-Classification hf_space

          # 2. Copy EVERYTHING from GitHub to the Space (except the .git folder)
          # The '.' refers to your GitHub Repo root.
          # This will now include your .gitignore and .ipynb files automatically.
          rsync -av --exclude='.git' --exclude='hf_space' ./ hf_space/

          # 3. Commit and Push to HuggingFace
          cd hf_space
          git add .
          git diff --cached --quiet || git commit -m "Auto deploy all files including notebooks and gitignore"
          
          git remote set-url origin https://nilotpaldhar2004:${HF_TOKEN}@huggingface.co/spaces/nilotpaldhar2004/Deep-Learning-for-Skin-Lesion-Classification
          git push origin main
