name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKENG }}
        run: |
          # 1. Setup credentials
          git config --global user.email "dharnilotpal31@gmail.com"
          git config --global user.name "Nilotpal Dhar"
          
          # 2. Add Hugging Face as a SECOND remote called 'hf'
          # This keeps 'origin' pointing to GitHub and 'hf' pointing to Spaces
          git remote add hf https://nilotpaldhar2004:${HF_TOKEN}@huggingface.co/spaces/nilotpaldhar2004/Deep-Learning-for-Skin-Lesion-Classification
          
          # 3. Force push the main branch to Hugging Face
          # Note: We push the local 'main' branch to the remote 'main' branch
          git push --force hf main
